#!/bin/bash
readarray -t words; declare -A counts; for word in "${words[@]}"; do counts["$word"]=$(( ${counts["$word"]} + 1 )); done; for word in "${words[@]}"; do if [[ ${counts["$word"]} -eq 1 ]]; then echo "$word"; fi; done | sort

